In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df=pd.read_csv("heart_clean_final.csv")

In [5]:
df

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     62    0   0       138  294.0    1        1      106      0      1.9   
1     58    0   0       100  248.0    0        0      122      0      1.0   
2     58    1   0       114  318.0    0        2      140      0      3.5   
3     54    1   0       122  286.0    0        0      116      1      3.2   
4     71    0   0       112  149.0    0        1      125      0      1.6   
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...   
178   60    0   2       120  178.0    1        1      100      0      0.0   
179   64    1   2       140  335.0    0        1      158      0      0.0   
180   68    0   2       120  211.0    0        0      115      0      1.5   
181   44    0   2       108  141.0    0        1      175      0      0.6   
182   59    1   3       160  273.0    0        0      125      0      0.0   

     slope  ca  thal  target  
0        1   3     2       0  
1        1   0     2       1  
2        0   3     1       0  
3        1   2     2       0  
4        1   0     2       1  
..     ...  ..   ...     ...  
178      2   0     2       1  
179      2   0     2       0  
180      1   0     2       1  
181      1   0     2       1  
182      2   0     2       0  

[183 rows x 14 columns]

In [7]:
indep=df.drop("target",axis=1)
dep=df["target"]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [17]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print("Classification Report:\n",clf_report)
print("Confusion Matrix:\n",cm)

Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.75      0.55        12
           1       0.93      0.76      0.83        49

    accuracy                           0.75        61
   macro avg       0.68      0.75      0.69        61
weighted avg       0.83      0.75      0.78        61

Confusion Matrix:
 [[ 9  3]
 [12 37]]


In [19]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)   
print("Classification Report:\n",clf_report)
print("Confusion Matrix:\n",cm)

Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.58      0.58        12
           1       0.90      0.90      0.90        49

    accuracy                           0.84        61
   macro avg       0.74      0.74      0.74        61
weighted avg       0.84      0.84      0.84        61

Confusion Matrix:
 [[ 7  5]
 [ 5 44]]


In [29]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print("Classification Report:\n",clf_report)
print("Confusion Matrix:\n",cm)

Classification Report:
               precision    recall  f1-score   support

           0       0.37      0.83      0.51        12
           1       0.94      0.65      0.77        49

    accuracy                           0.69        61
   macro avg       0.66      0.74      0.64        61
weighted avg       0.83      0.69      0.72        61

Confusion Matrix:
 [[10  2]
 [17 32]]


In [25]:
from sklearn.naive_bayes import CategoricalNB
classifier =CategoricalNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print("Classification Report:\n",clf_report)
print("Confusion Matrix:\n"cm)

IndexError: index 368 is out of bounds for axis 1 with size 355